### ISSUE TITLE
`process is not defined` error when bundled with webpack

### ISSUE THREAD

**Issue by th0r** [calvinmetcalf/process-nextick-args#11]
Code below throws `process is not defined` error if module is bundled by webpack for usage in browsers with `node: {process: false}` setting:
https://github.com/calvinmetcalf/process-nextick-args/blob/8407900951af3e7651fca50f127f0e4ddc01ad55/index.js#L3-L5

Adding `typeof process === 'undefined'` check to the condition should fix the issue.

**Comment by th0r** [comment]
Here is the PR: https://github.com/calvinmetcalf/process-nextick-args/pull/12

**Comment by calvinmetcalf** [comment]
ok I'll try to get to this tommorow

**Comment by calvinmetcalf** [comment]
and I'm getting to it now, all set
