### ISSUE TITLE
Please add license file

### ISSUE THREAD

**Issue by pnemade** [calvinmetcalf/process-nextick-args#2]
Hi,
   There is no information about licensing of this module. Can you please add license file?

Regards,
Parag.

**Comment by calvinmetcalf** [comment]
I do have a [license entry](https://github.com/calvinmetcalf/process-nextick-args/blob/295707643b4ed6667c1afb71ffb6101669b5dac2/package.json#L14) in the package.json so if you view it on npm it but shouldn't be a problem also adding a file

**Comment by calvinmetcalf** [comment]
13a91342e396fb9aebd85ad5c60bf08a1ba2b3ff

**Comment by pnemade** [comment]
Sorry I overlooked the package.json file. Let me give here more information about need of the license file. In Fedora Linux project we package upstream projects in rpm format. I have packaged this module in Fedora and it is going through its rpm package review. There its found this module do not provide actual license text which is needed for packaging this module in Fedora. So, I requested here.

Thank you for your quick response.

**Comment by pnemade** [comment]
just found license.md is not included in 1.0.2 released tarball

**Comment by calvinmetcalf** [comment]
Right I just added it

**Comment by calvinmetcalf** [comment]
Would it be helpful for me to cut a new release that has the  licence in it?

**Comment by pnemade** [comment]
Not necessary as I have included license file as extra source file in rpm spec file.
